import { ArrowUpRight } from 'lucide-react';
import { ScrollEffects } from '@/components/scroll-effects';
import { ScrollText } from '@/components/scroll-text';
import { MobileNavigation } from '@/components/mobile-navigation';
import { InternalFooter } from '@/components/internal-footer';

const procedures=[
  {title:'Cirurgia vascular',copy:'Procedimentos para condições venosas ou arteriais são definidos após avaliação clínica e exames adequados.',note:'O foco é tratar a causa identificada e orientar cada etapa do cuidado.',image:'/tratamento-cirurgia-vascular.webp',alt:'Dr. Ruan Reis com equipamento clínico',mediaClass:'procedure-media--clinical'},
  {title:'Varizes e microvarizes',copy:'Podem ser tratadas com diferentes recursos, de acordo com o tipo de vaso, sintomas e objetivos clínicos.',note:'A indicação depende de uma avaliação individual e de expectativas bem alinhadas.',image:'/tratamento-varizes-microvarizes.webp',alt:'Procedimento vascular na perna',mediaClass:'procedure-media--varizes'},
  {title:'Doppler vascular',copy:'Exame de ultrassom que ajuda a observar o fluxo sanguíneo e estruturas vasculares.',note:'É um recurso importante para diagnóstico, acompanhamento e planejamento terapêutico.',image:'/tratamento-doppler-vascular.webp',alt:'Exame Doppler vascular em andamento',mediaClass:'procedure-media--doppler'}
];
export default function Tratamentos(){return <main><ScrollEffects/><header className="site-header site-header-fixed"><a className="brand" href="/"><img src="/logo.png" alt="Dr. Ruan Reis, Cirurgião Vascular"/></a><nav aria-label="Navegação principal"><a href="/">Início</a><a href="/o-medico">O médico</a><a href="/tratamentos" aria-current="page">Tratamentos</a><a href="/r-veins">R-Veins</a></nav><MobileNavigation currentPath="/tratamentos"/><a className="button button-small" href="https://wa.me/5573981893485" target="_blank" rel="noreferrer">Agendar consulta <ArrowUpRight size={16}/></a></header><section className="treatments-hero section-wrap"><p className="eyebrow">Tratamentos</p><h1><ScrollText text="Informação para escolher com mais segurança."/></h1><p>Cada procedimento tem indicação, benefícios, limites e cuidados próprios. Esta página orienta a conversa; a definição do tratamento acontece na consulta.</p></section><section className="procedure-list section-wrap">{procedures.map(({title,copy,note,image,alt,mediaClass})=><article key={title} className="procedure scroll-reveal" data-reveal><div className="procedure-content"><p className="eyebrow">{title}</p><h2>{copy}</h2><p>{note}</p><a className="text-link" href="https://wa.me/5573981893485" target="_blank" rel="noreferrer">Tirar dúvidas na consulta <span>→</span></a></div><figure className={`procedure-media ${mediaClass}`}><img src={image} alt={alt}/></figure></article>)}</section><section className="clinical-note section-wrap scroll-reveal" data-reveal><p>Conteúdo informativo. Não substitui avaliação, diagnóstico ou orientação médica individual.</p></section><InternalFooter/></main>}
